matrix:
  fast_finish: true
  include:
    - name: "Build Web App"
      script:
        - yarn test
        - npx quasar build --mode pwa
      deploy:
        provider: script
        skip_cleanup: true
        script: npx netlify deploy --prod
        on:
          branch: master

    - name: "Build Mac Apps"
      os: osx
      script:
        - yarn test
        - npx quasar build --mode electron --publish always

    - name: "Build Windows Apps"
      os: windows
      script:
        - yarn test
        - npx quasar build --mode electron --publish always

    - name: "Build Linux Apps"
      os: linux
      script:
        - yarn test
        - npx quasar build --mode electron --publish always

language: node_js
node_js:
  - "lts/dubnium"
cache:
  yarn: true
  directories:
    - node_modules
env:
  global:
    - NODE_ENV=test
    - secure: pRTILWUkJrI528pD8Pb4bcla3inDKLr4nhiOWlYzuXjMlKznwJbmYY2YLnWYVeat33aB0Awcu9xqkxM62evZo29aw65gAXbyyqVqyE19FKUcY9CrYMo6Rt8tlTvRj3xaSG+oEki3rIKJQ4DH/zgiwajqgLV+MuhI1o59E8SWMmJQE2ypEqK0u4Bc/kjIwfV/O+zQimRyfsJucHu1ak+JfamOYhNv5alvh+wOnYKJZzTsMn3aUD0dDuG7WxRy64cCZDpanbZudwTdZmr4HNMEA5oeAhg+R8xqRUeV9TI/wWPOnS+sVF0qnGA/Dk2iYLu69Bn6TfHmsf7JklIMdnJpi5xFSaGCk85kAUXKNfXLYszahtoxjHGZJgxQGgOi7mAoJzFf9WaKjDepSGrk0Dx1ns3EyRiz+1ye+L+PIQ3akfkcbLv4R9Io0lXg9AQNoIbIeI0WjYpFyeqNdvt8iXym1yJ8fvF386ExLR6IHYFH4qjleCsT6SEiryKwd/FTwIEWTxqhdoRpky/5SYYAvtAL9/vnGVQWhyv/XlIcG/LNAd5L57BEypkxGPpaKc1mSbyrA5iTiBy7bjYdRY3+OCcuNlmXA0IRZEmdH6ihfuBKcqnhnbdZ284dxrcBabFCodMqypkEVTff5WZW7xVfglTVpTQE3u6TWP6YLpgpDBqCZ8A=
    - secure: cch/W1S89rLalKBasSqGm9vvjK62JVJmyp49GlSj+pKIGW0bSXhzlGhbrBfKKll/tErRv3BQEVFns9S0zPtkH22Wu44X00iXYtgbHe/Tfp3Cd7MZ6sQYkKHefb4dxirPvkWfzPcxlObQwmxcOaIq403D45yrgIoOBsaEqs0Icje8Ua9QPiBwD2EylAKenJWqJU0ZtwtnAvbv85R7tBKPS2lfXVEzQpH7ZoBm5F7bNpnR7bI7KOguMYhTKDvLqftbPHBUCBOwlEcbMFkk7AUDWU5SlOOllsV+7ygAB/rpH4Oq24odHGs0O3Qpck/tk0X5u40ankHXDNict72/6jbFTtGqNqhm0Yi36tb4ZG2oCDEi1G279NtufXO/ulGAFeCHEgqPXHEE11IuE5BQevQQvSLoDYlNZ6AIpdLkaTA++5NbKvT2hByega90pBqYIkUtIWuxrRL7oJDMXtM1xRPbTy9thql5ZZ32BMejYEEif7IeSySj0/9qaND6rPWLtqdC1S4Qew2d+rGrdYo0JHi04tjfb+BjK4NqcwQDkSIc4zpXINCM49cfG5ErvjdC0PHSaMPaDSoYIOjp73ZsCkOyBDxRFdQOHV29aWLrrpLsBbOTunEjkE8U9upXr+kxsXUY18A1izqhHIdzd153TK+TvxM6183II7nSPegkZvEM5eE=
