language: node_js
cache:
  yarn: true
  directories:
    - node_modules
env:
  global:
    - NODE_ENV=test

### Build
script:
  - yarn test
  - npx quasar build -m pwa

### Deploy
before_deploy:
  - npm install netlify-cli -g
deploy:
  provider: script
  script: netlify deploy --dir=dist/pwa --prod
  on:
    branch: master
