# Copy this file into one without .sample part and then populate it with actual values.
# Then you can create secret, by using command
# `sem create -f path/to/this/file`
# More info https://docs.semaphoreci.com/article/66-environment-variables-and-secrets
apiVersion: v1beta
kind: Secret
metadata:
  # Use this name to create this secret manually
  name: netlify-auth
data:
  files:
    # Download netlify cli `sudo npm install netlify-cli -g`
    # Authorize your terminal using `netlify login`.
    # This will create ~/.netlify/config.json which we'll use soon.
    #
    - path: ~/.netlify/config.json
      # Could be created by
      # - `base64 ~/.netlify/config.json`
      content: ewoJInRlbGVtZXRyeURpc2FibGVkIjogZmFsc2UsCgkiY2xpSWQiOiAiNDY0N2I0MDgtMTFhNS00NGMyLTgzOWEtNjJjN2Q2Mjg4YTlhIiwKCSJ1c2VySWQiOiAiNWQxY2NmMTk4OTM3NGJmMjBmZjNjMWE2IiwKCSJ1c2VycyI6IHsKCQkiNWQxY2NmMTk4OTM3NGJmMjBmZjNjMWE2IjogewoJCQkiaWQiOiAiNWQxY2NmMTk4OTM3NGJmMjBmZjNjMWE2IiwKCQkJIm5hbWUiOiAiUm9tYWluIEJhcmlzc2F0IiwKCQkJImVtYWlsIjogImJhcmlzc2F0QGdtYWlsLmNvbSIsCgkJCSJhdXRoIjogewoJCQkJInRva2VuIjogIjFjYWQ0ZTczMmI1ZjFmMmViYzNmMDllNDZiZDY4NzQzMTM2YzJiNzFjYTU0OGQ4YzQ1YTZmNjk4YTBhMzc2OTYiLAoJCQkJImdpdGh1YiI6IHt9CgkJCX0KCQl9Cgl9Cn0=

    # If you haven't already, create a "New site from Git" in Netlify.
    # Link your CLI to the project which you created, using `netlify link`.
    # This will create ~/.netlify/state.json which we'll use soon.
    #
    - path: ~/.netlify/state.json
      # Could be created by
      # - `base64 .netlify/state.json`
      content: ewoJInNpdGVJZCI6ICIzYjQzYzQyNi05NWMxLTRmNzEtODUzYi03OGMxMzc1YWZiOWYiCn0=
