# .semaphore/pwa-netlify.yml
version: v1.0
name: Deploy PWA to Netlify
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
blocks:
  - name: 🏁 Deploy
    task:
      # Mount a secret which defines /home/semaphore/.netlify/config.json and
      # /home/semaphore/.netlify/state.json.
      # By mounting it, we make the files available in the job environment.
      #
      # Follow the comments in ./secrets/netlify-secret.sample.yml
      #
      # For info on creating secrets, see:
      # https://docs.semaphoreci.com/article/66-environment-variables-and-secrets
      secrets:
        - name: netlify-authentication
      jobs:
        - name: Copy to netlify
          commands:
            - npm install netlify-cli -g
            - cache restore pwa-build
            - netlify deploy --dir=dist/pwa --prod
